---
# Inventaire pour GLPI
all:
  children:
    glpi_servers:
      hosts:
        glpi-server:
          ansible_host: 192.168.1.100          # Remplacez par votre IP
          ansible_user: debian                 # Remplacez par votre utilisateur
          ansible_password: votre_mot_de_passe # Remplacez par votre mot de passe SSH
          ansible_become: yes
          ansible_become_password: votre_mot_de_passe # Remplacez par votre mot de passe sudo
