---
# Inventaire pour GLPI
all:
  children:
    glpi_servers:
      hosts:
        glpi-server:
          ansible_host: 192.168.1.226
          ansible_user: debian
          ansible_password: Epsi2022!
          ansible_become: yes
          ansible_become_password: Epsi2022!
